# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d414010b1432b8c8571aa7986c67c6846bc3cc045dfccdee2009c28fec1485e50050a2016732e298b2289268365e53099d370f4e885e8ce2de669f4b66b424f

test:
  secret_key_base: f4ae0fb4e19c2ef1a8a4e0576d5abcd76d1f11cd46d32c099cd5f4287f1f4e0b501085abd40b2f0ffd7883df8073f62b81473e8e93a2533f8b31de06862d52a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
